/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131316',
        'surface-dim': '#131316',
        'surface-bright': '#39393c',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        'surface-variant': '#353438',
        'on-surface': '#e4e1e6',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#e4e1e6',
        'inverse-on-surface': '#303033',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'primary': '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'system-accent': '#3b82f6',
        'secondary': '#c6c5cf',
        'on-secondary': '#2f3038',
        'secondary-container': '#4a4b53',
        'on-secondary-container': '#bcbbc5',
        'tertiary': '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#00a572',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
      },
      spacing: {
        'gutter': '0.75rem',
        'gutter-compact': '0.5rem',
        'margin': '1rem',
        'margin-window': '0.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.375rem',
        'space-md': '0.5rem',
        'space-lg': '0.75rem',
        'space-xl': '1rem',
        'space-2xl': '1.5rem',
      }
    },
  },
  plugins: [],
}
